package ru.bright.bot.service.callbacks;

public enum CallBackDates {
    SEMINARS,
    OWNSEMINARS,
    JOINED_SEMINARS,
    BACK_TO_CATEGORIES,
    EDIT_TIME,
    EDIT_OWNER_FIO,
    EDIT_SEMINAR_NAME,
    EDIT_ADDITIONAL_INFO,
    LEAVE_SEMINAR,
    EDIT_SEMINAR,
    SET_FIO,
    OWN_SEMINARS_ADDITIONAL_INFORMATION,
    OWN_SEMINARS_ADDITIONAL_INFORMATION_PAGE,
    DELETE_CURRENT_SEMINAR,
    DELETE_SEMINAR,

    DELETE_SEMINAR_ACCEPT,
    MANAGE_SEMINAR,
    SEMINAR_PANEL,
    DELETE_SEMINAR_DENY,
    CREATE_SEMINAR_CONFIRM,
    NOTIFY_PARTICIPANTS,
    SEMINAR_NOTIFIES,
    SEMINAR_NOTIFIES_PAGE,
    SEMINAR_TIME_NOTIFIES,
    TIME_NOTIFY,
    LEAVE_SEMINAR_ACCEPT,
    LEAVE_SEMINAR_DENY,
    BACK_TO_PANEL,
    CREATE_SEMINAR_DENY;
}
